### ISSUE TITLE
Mapa Mental De La Wed 3.0

### ISSUE THREAD

**Issue by luzm23** [SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-luzm23#1]
[Mapa Mental De La Wed 3.0.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-luzm23/files/14671937/Mapa.Mental.De.La.Wed.3.0.pdf)

**Comment by Nelsy21** [comment]
20/20 calificado conforme a la rubrica.                                                                                    
Buen trabajo.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
